# Site settings
title: adamwong246.github.io
email: adamwong246@gmail.com
description: ""
baseurl: ""
url: "http://www.adamwong246.github.io"
github_url: "https://github.com/adamwong246/adamwong246.github.io"
twitter_username: adamwong246
github_username:  adamwong246

# Build settings
markdown: kramdown
permalink: pretty
