// Generated by CoffeeScript 1.6.3
(function() {
  var beautify_html, content_tree, dir, frontMatter, fs, glob, markdown, merge, mkdirp, path, treeMerge, util, writeFileWithIndifferentWrite;

  fs = require("fs");

  dir = require("node-dir");

  path = require("path");

  frontMatter = require("yaml-front-matter");

  markdown = require("markdown").markdown;

  merge = require("deepmerge");

  beautify_html = require("js-beautify").html;

  mkdirp = require("mkdirp");

  glob = require("glob");

  util = require("util");

  treeMerge = require('tree-merge');

  writeFileWithIndifferentWrite = function(dest, content) {
    mkdirp(dest.split("/").slice(0, -1).join("/"), function(err) {
      if (err) {
        console.error(err);
      } else {
        fs.writeFile(dest, content);
      }
    });
  };

  content_tree = treeMerge.apply(require('./_src/_blog/_.js'), glob.sync("./_src/_blog/**/*.md").map(function(e) {
    return path.relative("./_src/", e).split("/").reduceRight((function(p, c) {
      var b;
      b = {};
      b[c] = p;
      return b;
    }), merge(frontMatter.loadFront(e), {
      path: e
    }));
  }));

  console.log(JSON.stringify(content_tree));

  console.log(content_tree._blog["0"]["index.md"].title);

}).call(this);

/*
//@ sourceMappingURL=build.map
*/
